display lengthLeft
display leftArray[0]
display leftArray[1]
display leftArray[2]
display lengthRight
display rightArray[0]
display rightArray[1]
display rightArray[2]
display processedData->array[0]
display processedData->array[1]
display processedData->array[2]
display processedData->array[3]
display processedData->array[4]
display processedData->array[5]